# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems =
    let
      btrfs-mount-options = [
        "compress=zstd"
        "noatime"
        "discard=async"
        "space_cache=v2"
      ];
    in
    {
      "/" = {
        device = "/dev/disk/by-uuid/0184e3ee-792a-406f-98ea-ec99a16c6c5e";
        fsType = "btrfs";
        options = [ "subvol=root" ] ++ btrfs-mount-options;
      };
      "/old_roots" = {
        device = "/dev/disk/by-uuid/0184e3ee-792a-406f-98ea-ec99a16c6c5e";
        fsType = "btrfs";
        options = [ "subvol=old_roots" ] ++ btrfs-mount-options;
      };
      "/boot" = {
        device = "/dev/disk/by-uuid/8741-BFA8";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };
      "/nix" = {
        device = "/dev/disk/by-uuid/0184e3ee-792a-406f-98ea-ec99a16c6c5e";
        fsType = "btrfs";
        options = [ "subvol=nix" ] ++ btrfs-mount-options;
      };
      "/persist" = {
        device = "/dev/disk/by-uuid/0184e3ee-792a-406f-98ea-ec99a16c6c5e";
        fsType = "btrfs";
        options = [ "subvol=persist" ] ++ btrfs-mount-options;
      };
      "/persist-snapshots" = {
        device = "/dev/disk/by-uuid/0184e3ee-792a-406f-98ea-ec99a16c6c5e";
        fsType = "btrfs";
        options = [ "subvol=persist-snapshots" ] ++ btrfs-mount-options;
      };
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/1563cd08-9a71-4a87-8d93-5fdb28b727c0"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
